IncrementalProducer listeners (IncrementalCycleListener)
Netflix/hollow pull request #153
Opened 2018-01-19 16:23 UTC by rpalcolea

Introduces `IncrementalCycleListener`

2018-01-19 20:04 UTC, kineshsatiya commented
I wonder if we should have an interface for the producer with two implementations - CycleProducer & IncrementalCycleProducer. Some abstraction would be nice. I think the same thing would apply to listeners. I see that we have IncrementalListener in ListenerSupport, and they are only used in IncrementalHollowProducer. We should probably use separate them out. What your thoughts on this @toolbear and @rpalcolea ?

2018-01-19 20:08 UTC, rpalcolea commented
Hi @kineshsatiya ,

I think this aligns with https://github.com/Netflix/hollow/issues/154. What are your thoughts on that? I wanted to re-use `ListenerSupport` because is part of the `producer` package... and yes, seems like the `IncrementalListener` is only used by the incremental producer. I think consolidating things into one interface with two implementations would be nice... don't know if that's something in a short term though.

2018-01-19 23:59 UTC, kineshsatiya commented
Hi @rpalcolea , I'll review the current PR. If we can come up with a better design now, we can start with that. However, we can re-visit the design, when we start on next major release of Hollow.

2018-01-22 22:12 UTC, rpalcolea commented
sounds good @kineshsatiya

2018-03-22 20:47 UTC, rpalcolea commented
Hi @toolbear,

Just added something to this PR that could be helpful for others: `cycleMetadata`

The idea is that users could attach metadata to each cycle:

```
 HashMap<String, Object> cycleMetadata = new HashMap<>();
        cycleMetadata.put("foo", "bar");
        incrementalProducer.addCycleMetadata(cycleMetadata);
```

then in the listener we will have:

```void onCycleComplete(IncrementalCycleStatus status, long elapsed, TimeUnit unit, HashMap<String, Object> cycleMetadata)```

Then, users could use that metadata to take action at listener level. 

In our case we would like to attach some metadata from our source system and trigger actions depending on success or failure.

2018-04-24 01:43 UTC, ghost requested changes
Looks good. Some small changes and one medium change around how to expose the metadata to listeners.

2018-04-24 01:43 UTC, ghost commented on hollow/src/main/java/com/netflix/hollow/api/producer/AbstractIncrementalCycleListener.java
> +    public void onCycleComplete(IncrementalCycleStatus status, long elapsed, TimeUnit unit, HashMap<String, Object> cycleMetadata) { }
Expose `Map<String,Object>` instead of `HashMap` in the public API

2018-04-24 01:43 UTC, ghost commented on hollow/src/main/java/com/netflix/hollow/api/producer/AbstractIncrementalCycleListener.java
> +    public void onCycleComplete(IncrementalCycleStatus status, long elapsed, TimeUnit unit, HashMap<String, Object> cycleMetadata) { }
Instead of adding new argument to the listener interface, we've tended to make additional info available through the already passed in cycle status class (in this case `IncrementalCycleStatus`). This has the added bonus of avoiding a breaking change (not that that is necessary given this is an experimental API).

2018-04-24 01:43 UTC, ghost commented on hollow/src/main/java/com/netflix/hollow/api/producer/HollowIncrementalProducer.java
> +    private final HashMap<String, Object> cycleMetadata;
This can be declared as `Map`.

2018-04-24 01:43 UTC, ghost commented on hollow/src/main/java/com/netflix/hollow/api/producer/HollowIncrementalProducer.java
> +    public void addCycleMetadata(HashMap<String, Object> metadata) {
Should this be `addAllCycleMetadata` with the addition of a `addCycleMetadata(String key, Object value)` method?

2018-04-24 01:43 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/api/producer/IncrementalCycleListener.java
> +    public void onCycleComplete(IncrementalCycleStatus status, long elapsed, TimeUnit unit, HashMap<String, Object> cycleMetadata);
`Map` instead of `HashMap`

2018-04-24 01:43 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/api/producer/IncrementalCycleListener.java
> +    public void onCycleFail(IncrementalCycleStatus status, long elapsed, TimeUnit unit, HashMap<String, Object> cycleMetadata);
`Map` instead of `HashMap`

2018-04-24 01:43 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/api/producer/ListenerSupport.java
> +    void fireIncrementalCycleComplete(long version, long recordsAddedOrModified, long recordsRemoved, HashMap<String, Object> cycleMetadata) {
`Map` instead of `HashMap`

2018-04-24 01:43 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/api/producer/ListenerSupport.java
> +    void fireIncrementalCycleFail(Throwable cause, long recordsAddedOrModified, long recordsRemoved, HashMap<String, Object> cycleMetadata) {
`Map` instead of `HashMap`

2018-04-24 01:43 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/api/producer/ListenerSupport.java
> +        IncrementalCycleStatus.Builder icsb = new IncrementalCycleStatus.Builder().success(version, recordsAddedOrModified, recordsRemoved);
This is where an `icsb.withMetadata(cycleMetadata)` would go instead of passing it directly to listener callback.

2018-04-24 02:38 UTC, rpalcolea commented
Hi @toolbear ,

Thanks for the feedback. 

Made the changes to use `Map` and also to include `cycleMetadata` as part of `IncrementalCycleStatus`

2018-04-24 02:39 UTC, rpalcolea commented
Also, I'd like to get this one (bigger) in first in order to fix conflicts on https://github.com/Netflix/hollow/pull/152 and https://github.com/Netflix/hollow/pull/182 if that's ok with you @toolbear

2018-04-24 02:57 UTC, ghost requested changes

2018-04-24 02:57 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/api/producer/HollowIncrementalProducer.java
> +    public void addAllCycleMetadata(HashMap<String, Object> metadata) {
Missed one 😉 

Use `Map` here, too.

2018-04-24 03:02 UTC, merged