added metrics and blob storage cleaner docs
Netflix/hollow pull request #218
Opened 2018-05-04 14:38 UTC by rpalcolea

Hi @toolbear @akhaku,

This PR adds docs for `BlobStorageCleaner` and `HollowMetricsCollector`.

I'd like to add something around `HollowIncrementalProducer` but I wanted to check with you first if it makes sense to replace the https://hollow.how/advanced-topics/#delta-based-producer-input section

Please let me know your thoughts

2018-06-01 19:32 UTC, ghost requested changes

2018-06-01 19:32 UTC, toolbear commented on docs/tooling.md
> +```groovy
`java` ?

2018-06-02 00:11 UTC, rpalcolea commented on docs/tooling.md
> +```groovy
Oops! Will change to java

2018-06-07 13:17 UTC, rpalcolea commented
Hi @toolbear ,

Replaced the groovy code examples with Java

2018-06-18 18:55 UTC, merged