Catch Exception rather than Throwable to prevent an invalid write state
Netflix/hollow pull request #232
Opened 2018-06-04 16:46 UTC by duro1

Receiving an OutOfMemoryError in the HollowWriteStateEngine.resetToLastPrepareForNextCycle method resulted in having an empty write state. After this occurred, future snapshots published as if they were the initial snapshot, losing all previous states data.

Allow JVM level Errors to propagate rather than be wrapped into a RuntimeException that could more easily be incorrectly logged and ignored

2018-06-04 16:50 UTC, duro1 commented
@toolbear @akhaku Please take a look at the PR comments for the motivation of this change and let me know if you have any comments/concerns.
CC: @rpalcolea @tinetti

2018-06-12 08:45 UTC, ghost requested changes

2018-06-12 08:45 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/api/consumer/fs/HollowFilesystemAnnouncementWatcher.java
> +                } catch (Exception ex) {
I wonder if we want this idiom:

```java
try {
  // ...
} catch (Exception ex) {
  log.log(WARNING, ...);
} catch (Throwable th) {
  log.log(ERROR, ...);
  throw th;
}
```

Just to leave a little clearer breadcrumb behind.

2018-06-12 08:45 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/core/write/HollowWriteStateEngine.java
> +            throw new RuntimeException(ex);
We've started replacing rethrowing as `HollowException` or a subclass of `HollowException` just to make forensics a little clearer. We change them as we come across them while making other related changes.

2018-06-14 03:55 UTC, duro1 reviewed
@toolbear Thanks for the review comments. PR has been updated.  Please take another look

2018-06-18 19:03 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/core/write/HollowWriteStateEngine.java
> +            throw new HollowWriteStateException("Unable to restore write state from read state engine", e);
👍

2018-06-18 19:03 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/core/write/HollowWriteStateEngine.java
> +            throw new HollowWriteStateException("Failed to prepare for write", ex);
👍

2018-06-18 19:03 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/core/write/HollowWriteStateEngine.java
> +            throw new HollowWriteStateException("Failed to prepare for next cycle", ex);
👍

2018-06-18 19:03 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/core/write/HollowWriteStateEngine.java
> +            throw new HollowWriteStateException("Unable to reset to the prior version of the write state", ex);
👍

2018-06-18 19:04 UTC, ghost approved these changes

2018-06-18 19:04 UTC, merged