use FileOutputStream and FileInputstream for roundTripStateEngine in HollowHistoryUI
Netflix/hollow pull request #237
Opened 2018-06-11 19:48 UTC by rpalcolea

2018-06-11 19:53 UTC, rpalcolea commented
Thoughts on this @toolbear ?

2018-06-18 19:29 UTC, ghost requested changes
Looks good. Can you make the tweaks suggested?

2018-06-18 19:29 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/tools/history/keyindex/HollowHistoryKeyIndex.java
> +            Path tmpFile = Files.createTempFile("tmp", "history");
Do something like `Files.createTempFile("roundtrip", "snapshot")`. This would make a file like `${java.io.tmpdir}/roundtripXXXXXX.snapshot`

2018-06-18 19:29 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/tools/history/keyindex/HollowHistoryKeyIndex.java
> +                FileOutputStream fileOutputStream = new FileOutputStream(tmpFile.toFile());
`Files.newOutputStream(tmpFile)` is idiomatic.

2018-06-18 19:29 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/tools/history/keyindex/HollowHistoryKeyIndex.java
> +                reader.readSnapshot(new FileInputStream(tmpFile.toFile()));
`Files.newInputStream(tmpFile)` is idiomatic.

2018-06-18 19:29 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/tools/history/keyindex/HollowHistoryKeyIndex.java
> +                FileOutputStream fileOutputStream = new FileOutputStream(tmpFile.toFile());
ditto above

2018-06-18 19:29 UTC, toolbear commented on hollow/src/main/java/com/netflix/hollow/tools/history/keyindex/HollowHistoryKeyIndex.java
> +                reader.applyDelta(new FileInputStream(tmpFile.toFile()));
ditto above

2018-06-18 19:43 UTC, rpalcolea commented
Hi @toolbear,

Updated the code based on your comments! Thanks!

2018-07-05 22:22 UTC, merged