Feature/hollow producer restore
Netflix/hollow pull request #47
Opened 2017-04-05 18:15 UTC by davesu

Enhancement to enable HollowProducer to restore blob even after it has existing non empty state 

- Restore after it was already published states
- Add ability to indicate whether Restore Failure is Fatal (throw RuntimeException)
- Add support for announcement metadata
-

2017-04-05 19:25 UTC, dkoszewnik requested changes

2017-04-05 19:25 UTC, dkoszewnik commented on hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java
> +        public void announce(long stateVersion, Map<String, String> metadata);
Adding metadata tags to announcement feels like unnecessary cognitive load -- we should avoid this. The concept of announcement should remain simple: http://hollow.how/producer-consumer/#announcing-the-state. Specific implementations are free to introduce additional complexity as necessary, but that complexity shouldn't leak into the core producer API.

2017-04-05 19:25 UTC, dkoszewnik commented on hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java
> +    private class WriteEngineWrapper {
I'd like to understand more about why the WriteEngineWrapper is necessary -- if we can do without it and if not, whether there is a better name to express its purpose

2017-04-05 19:25 UTC, dkoszewnik commented on hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java
> +    public void setRestoreFailureFatal(boolean isFatal) {
I think that the behavior of the system when restore fails should be defined by the caller to restore, rather than have to configure it here.

2017-04-05 21:38 UTC, davesu commented on hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java
> +        public void announce(long stateVersion, Map<String, String> metadata);
This was implemented for the use case to notify client about schema changes on delta.   Any suggestions on an alternative way to propagate this information?

2017-04-05 21:41 UTC, davesu commented on hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java
> +    private class WriteEngineWrapper {
I agree a better name for this class would be good.  

The purpose was to encapsulate classes that needs to be changed on a Restore.  Originally I was going to use WriteState but that is already used.   

Let's try to come up with something better.

2017-04-05 21:41 UTC, davesu commented on hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java
> +    public void setRestoreFailureFatal(boolean isFatal) {
Ok, let me try that.

2017-04-10 20:17 UTC, ghost approved these changes
Looks good.

It still feels like the code for management state engines and object mappers may find a better home in `WriteStateImpl`, but I think it's appropriate to do that in a separate PR to keep this change more surgical.

2017-04-10 22:05 UTC, merged